### ISSUE TITLE
Complete Test Data

### ISSUE THREAD

**Issue by bosterholz** [metagenomics/bioPipeline#47]
Get a minimal set of data, to simulate a complete pipeline run.

**Comment by pbelmann** [comment]
Thank for creating this issue @bosterholz. I suggest that we do not upload the test data to our github repo. Instead we could later create a bootstrap script which downloads the data from dropbox and runs the necessary tests (e.g unit, BDD, ... tests).

**Comment by pbelmann** [comment]
@bosterholz  Currently the cucumber tests are executed with the following data:
https://github.com/metagenomics/bioPipeline/tree/master/features/data

If you agree with this set, please close this Issue. Otherwise please update  the data files and also the feature test: https://github.com/metagenomics/bioPipeline/blob/master/features/nextflow.feature .

**Comment by bosterholz** [comment]
Currently, the test files produce only one real hit. There should be at least one hit of each category. I will expand the test files, to fit this criteria.
